<h2 id="exercises">Exercises</h2>
<p>In your <code>numpy-pandas-visualization-exercises</code> repo, create a file named <code>numpy_exercises.py</code> for this exercise.</p>
<p>Use the following code for the questions below:</p>
<div class="highlight"><pre><span></span>a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
</pre></div>

<ol>
<li>
<p>How many negative numbers are there?</p>
</li>
<li>
<p>How many positive numbers are there?</p>
</li>
<li>
<p>How many even positive numbers are there?</p>
</li>
<li>
<p>If you were to add 3 to each data point, how many positive numbers would
   there be?</p>
</li>
<li>
<p>If you squared each number, what would the new mean and standard deviation
   be?</p>
</li>
<li>
<p>A common statistical operation on a dataset is <strong>centering</strong>. This means to
   adjust the data such that the mean of the data is 0. This is done by
   subtracting the mean from each data point. Center the data set. See <a href="https://www.theanalysisfactor.com/centering-and-standardizing-predictors/">this link</a> for more on centering.</p>
</li>
<li>
<p>Calculate the z-score for each data point. Recall that the z-score is given
   by:</p>
<div>
<div class="MathJax_Preview">
Z = \frac{x - \mu}{\sigma}
</div>
<script type="math/tex; mode=display">
Z = \frac{x - \mu}{\sigma}
</script>
</div>
</li>
<li>
<p>Copy the setup and exercise directions from <a href="https://gist.github.com/ryanorsinger/c4cf5a64ec33c014ff2e56951bc8a42d">More Numpy Practice</a> into your <code>numpy_exercises.py</code> and add your solutions.</p>
</li>
</ol>
<p><strong> Awesome Bonus </strong>
For much more practice with numpy, Go to <code>https://github.com/rougier/numpy-100</code> and clone the repo down to your laptop. Next, go to <code>https://github.com/new</code> to make a new repo. Name it <code>numpy-100</code>, and follow the directions to "push an existing repository from the command line" so that you can push up your changes to your own account.</p>
                
                  
                
              

In [2]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?


In [ ]:
1. How many negative numbers are there

In [8]:
a[a<0]

array([-2, -1, -6, -7])

In [15]:
len(a[a<0])

4

2. How many positive numbers are there?

In [3]:
a[a>0]

array([ 4, 10, 12, 23,  3])

In [4]:
len(a[a>0])

5

In [5]:
print(a[a>0].size)

5


In [6]:
print(a[a>0].shape)

(5,)


3. How many even positive numbers are there?

In [11]:
a[(a > 0) & (a % 2 ==0)]

array([ 4, 10, 12])

In [17]:
len(a[(a > 0) & (a % 2 ==0)])

3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [12]:
b=a+3
b[b>0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [18]:
len(b[b>0])

10

5. If you squared each number, what would the new mean and standard deviation be?

In [8]:
c = a **2
c.mean(), c.std()

(74.0, 144.0243035046516)

In [9]:
{
    'mean': c.mean(),
    'standard_deviation': c.std()
}

{'mean': 74.0, 'standard_deviation': 144.0243035046516}

6. A common statistical operation on a dataset is <strong>centering</strong>. This means to
   adjust the data such that the mean of the data is 0. This is done by
   subtracting the mean from each data point. Center the data set. See <a href="https://www.theanalysisfactor.com/centering-and-standardizing-predictors/">this link</a> for more on centering.

In [3]:
np.mean(a)

3.0

In [12]:
a -=3 
a

array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

In [10]:
centered = a- a.mean()

In [11]:
centered.mean()

0.0

In [13]:
a.mean()


0.0

7. Calculate the z-score for each data point. Recall that the z-score is given
   by:</p>
<div>
<div class="MathJax_Preview">
Z = \frac{x - \mu}{\sigma}
</div>
<script type="math/tex; mode=display">
Z = \frac{x - \mu}{\sigma}
</script>
</div>
</li>

In [14]:
(a-a.mean())/a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. <p>Copy the setup and exercise directions from <a href="https://gist.github.com/ryanorsinger/c4cf5a64ec33c014ff2e56951bc8a42d">More Numpy Practice</a> into your <code>numpy_exercises.py</code> and add your solutions.</p>

In [5]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list


In [17]:
sum_of_a = np.sum(a)
sum_of_a

55

Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list


In [18]:
min_of_a = np.min(a)
min_of_a

1

Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [19]:
max_of_a = np.max(a)
max_of_a

10

Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list


In [21]:
mean_of_a = np.mean(a)
mean_of_a

5.5

Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [29]:
product_of_a = np.product(a)
product_of_a

3628800

Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]


In [21]:
squares_of_a = a**2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers


In [7]:
is_odd = a % 2 == 1
odds_in_a = a[is_odd]
odds_in_a

array([1, 3, 5, 7, 9])

Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [9]:
is_even = a % 2 == 0
evens_in_a = a[is_even]
evens_in_a

array([ 2,  4,  6,  8, 10])

---

What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

b = [ [3, 4, 5], [6, 7, 8] ]

In [13]:
b = np.matrix([ [3, 4, 5], [6, 7, 8] ])

In [11]:
b

matrix([[3, 4, 5],
        [6, 7, 8]])

Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. Hint, you'll first need to make sure that the "b" variable is a numpy array

      sum_of_b = 0
          for row in b:
      sum_of_b += sum(row)

In [14]:
sum_of_b=np.sum(b)
sum_of_b

33

- Exercise 2 - refactor the following to use numpy. 

        min_of_b = min(b[0]) 
            if min(b[0]) <= min(b[1]) 
        else min(b[1])  

In [15]:
min_of_b = np.min(b)
min_of_b

3

- Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
        max_of_b = max(b[0]) 
            if max(b[0]) >= max(b[1]) 
            else max(b[1])

In [17]:
max_of_b = np.max(b)
max_of_b

8

- Exercise 4 - refactor the following using numpy to find the mean of b
    mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [18]:
mean_of_b = np.mean(b)
mean_of_b

5.5

- Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

      product_of_b = 1
      for row in b:
          for number in row:
              product_of_b *= number

In [19]:
product_of_b = np.product(b)
product_of_b

20160

- Exercise 6 - refactor the following to use numpy to find the list of squares

         squares_of_b = []
         for row in b:
             for number in row:
                 squares_of_b.append(number**2)

In [23]:
squares_of_b = np.square(b)
squares_of_b

matrix([[ 9, 16, 25],
        [36, 49, 64]])

- Exercise 7 - refactor using numpy to determine the odds_in_b
          odds_in_b = []
          for row in b:
              for number in row:
                  if(number % 2 != 0):
                      odds_in_b.append(number)

In [25]:
is_odd = b % 2 == 1
odds_in_b = b[is_odd]
odds_in_b

matrix([[3, 5, 7]])

- Exercise 8 - refactor the following to use numpy to filter only the even numbers

         evens_in_b = []
         for row in b:
             for number in row:
                 if(number % 2 == 0):
                     evens_in_b.append(number)

In [26]:
is_even = b % 2 == 0
evens_in_b = b[is_even]
evens_in_b

matrix([[4, 6, 8]])

- Exercise 9 - print out the shape of the array b.

In [27]:
np.shape(b)

(2, 3)

- Exercise 10 - transpose the array b.

In [28]:
np.transpose(b)

matrix([[3, 6],
        [4, 7],
        [5, 8]])

- Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [29]:
np.reshape?

In [30]:
np.reshape(b,(1,6))

matrix([[3, 4, 5, 6, 7, 8]])

In [14]:
b.flatten()

matrix([[3, 4, 5, 6, 7, 8]])

- Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [31]:
np.reshape(b,(6,1))

matrix([[3],
        [4],
        [5],
        [6],
        [7],
        [8]])

---

### Setup 3
    c = [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]

### HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [32]:
c = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

- Exercise 1 - Find the min, max, sum, and product of c.

In [33]:
np.min(c)

1

In [34]:
np.max(c)

9

In [35]:
np.sum(c)

45

In [36]:
np.product(c)

362880

- Exercise 2 - Determine the standard deviation of c.

In [37]:
np.std(c)

2.581988897471611

- Exercise 3 - Determine the variance of c.

In [38]:
np.var(c)

6.666666666666667

- Exercise 4 - Print out the shape of the array c

In [40]:
np.shape(c)

(3, 3)

- Exercise 5 - Transpose c and print out transposed result.

In [41]:
np.transpose(c)

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

- Exercise 6 - Get the dot product of the array c with c.

In [42]:
np.dot?


In [44]:
np.dot(c,c)

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

- Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [52]:
np.sum(np.multiply(c, np.transpose(c)))

261

- Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [56]:
np.product(np.multiply(c, np.transpose(c)))

131681894400

---

### Setup 4
        d = [
            [90, 30, 45, 0, 120, 180],
            [45, -90, -30, 270, 90, 0],
            [60, 45, -45, 90, -45, 180]
        ]

In [57]:
d = np.matrix([
        [90, 30, 45, 0, 120, 180],
        [45, -90, -30, 270, 90, 0],
        [60, 45, -45, 90, -45, 180]
    ])

- Exercise 1 - Find the sine of all the numbers in d

In [59]:
np.sin(d)

matrix([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
         -0.80115264],
        [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
          0.        ],
        [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
         -0.80115264]])

- Exercise 2 - Find the cosine of all the numbers in d

In [61]:
np.cos(d)

matrix([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
         -0.59846007],
        [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
          1.        ],
        [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
         -0.59846007]])

- Exercise 3 - Find the tangent of all the numbers in d

In [62]:
np.tan(d)

matrix([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
          1.33869021],
        [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
          0.        ],
        [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
          1.33869021]])

- Exercise 4 - Find all the negative numbers in d

In [63]:
d[d<0]

matrix([[-90, -30, -45, -45]])

- Exercise 5 - Find all the positive numbers in d


In [64]:
d[d>0]

matrix([[ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180]])

- Exercise 6 - Return an array of only the unique numbers in d.

In [65]:
np.unique(d)

matrix([[-90, -45, -45, -30,   0,   0,  30,  45,  45,  45,  60,  90,  90,
          90, 120, 180, 180, 270]])

- Exercise 7 - Determine how many unique numbers there are in d.

In [68]:
np.shape(np.unique(d))

(1, 18)

- Exercise 8 - Print out the shape of d.

In [70]:
np.shape(d)

(3, 6)

- Exercise 9 - Transpose and then print out the shape of d.

In [71]:
np.shape(np.transpose(d))

(6, 3)

- Exercise 10 - Reshape d into an array of 9 x 2

In [72]:
np.reshape(d, (9,2))

matrix([[ 90,  30],
        [ 45,   0],
        [120, 180],
        [ 45, -90],
        [-30, 270],
        [ 90,   0],
        [ 60,  45],
        [-45,  90],
        [-45, 180]])

<strong> Awesome Bonus </strong>
For much more practice with numpy, Go to <code>https://github.com/rougier/numpy-100</code> and clone the repo down to your laptop. Next, go to <code>https://github.com/new</code> to make a new repo. Name it <code>numpy-100</code>, and follow the directions to "push an existing repository from the command line" so that you can push up your changes to your own account.</p>